server:
  port: ${APP_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:5432/${DB_NAME:vorotof}
    username: ${DB_USERNAME:vorotof}
    password: ${DB_PASSWORD:vorotof}
  liquibase:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:5432/${DB_NAME:vorotof}
    user: ${DB_USERNAME:vorotof}
    password: ${DB_PASSWORD:vorotof}
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true

app:
  telegram:
    token: ${TELEGRAM_BOT_TOKEN:telegramToken}
    username: ${TELEGRAM_BOT_USERNAME:telegramUsername}