server:
  port: ${APP_PORT:8080}

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:file:./data/buyers
    driverClassName: org.h2.Driver
    username: buyers
    password: buyers
  liquibase:
    url: jdbc:h2:file:./data/buyers
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true

app:
  telegram:
    token: ${TELEGRAM_BOT_TOKEN:telegramToken}
    username: ${TELEGRAM_BOT_USERNAME:telegramUsername}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE