version: "3.7"
services:

  # БД
  db:
    image: postgres:12-alpine
    container_name: db
    hostname: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: vorotof
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: vorotof
      PGDATA: /var/lib/postgresql/data/vorotof
    volumes:
      - postgres-vorotof-advance-report:/var/lib/postgresql/data/vorotof
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=200"]
    networks:
      - vorotof-advance-report
    healthcheck:
      test: PGPASSWORD=vorotof psql -d vorotof -U vorotof -w -c '\q'
      interval: 20s
      timeout: 10s

  # PgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "9090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: vorotof@vorotof-advance-report.ru
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmindata:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    networks:
      - vorotof-advance-report

  app:
    container_name: app
    hostname: app
    image: croacker/s-vorotof-advance-report:${IRK_BUYERS_CLUB_VERSION}
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_HOST: db
      DB_NAME: vorotof
      DB_USERNAME: vorotof
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
    depends_on:
       - db
    networks:
       - vorotof-advance-report

networks:
  vorotof-advance-report:
    driver: bridge

volumes:
  postgres-vorotof-advance-report:
    external: false
  pgadmindata:
