version: "3.7"
services:

  # БД
  db:
    image: postgres:12-alpine
    container_name: db
    hostname: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: buyers
      POSTGRES_PASSWORD: buyers
      POSTGRES_DB: buyers
      PGDATA: /var/lib/postgresql/data/buyers
    volumes:
      - postgres-vorotof-advance-report:/var/lib/postgresql/data/buyers
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=200"]
    networks:
      - vorotof-advance-report
    healthcheck:
      test: PGPASSWORD=buyers psql -d buyers -U buyers -w -c '\q'
      interval: 20s
      timeout: 10s

  # PgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "9090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: buyers@vorotof-advance-report.ru
      PGADMIN_DEFAULT_PASSWORD: buyers
    volumes:
      - pgadmindata:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    networks:
      - vorotof-advance-report

networks:
  vorotof-advance-report:
    driver: bridge

volumes:
  postgres-vorotof-advance-report:
    external: false
  pgadmindata:
